apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      imagePullSecrets:
        - name: ghcr-login
      containers:
      - name: go-api
        image: ghcr.io/dlln9001/event-processing-go-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: KAFKA_HOST
          valueFrom:
            configMapKeyRef:
              name: shared-config
              key: KAFKA_HOST