apiVersion: v1
kind: Service
metadata:
  name: worker
spec:
  type: NodePort
  selector:
    app: worker
  ports:
    - protocol: TCP
      port: 8080        # Port other pods use
      targetPort: 8080  # Port the container listens on
      nodePort: 30080